message AF_SRV_TraspasoAfore_doc_dt_comparador {
optional  AF_SRV_TraspasoAfore_doc_dt_comparador_input input = 1;
optional  AF_SRV_TraspasoAfore_doc_dt_comparador_output output = 2;
optional  AF_SRV_TraspasoAfore_doc_dt_comparador_compuertas compuertas = 3;
optional  pub_publish_envelope _env = 536870910;
}
message AF_SRV_TraspasoAfore_doc_dt_comparador_compuertas {
optional  string tieneExpEnrolamiento = 1;
optional  string resultadoOperacion = 2;
}
message AF_SRV_TraspasoAfore_doc_dt_comparador_input {
optional  string sessionID = 1;
optional  string sessionDialogIdentification = 2;
optional  string noSolicitud = 3;
optional  string noAsesor = 4;
optional  string tipoSeguridadSocial = 5;
optional  string nss = 6;
optional  AF_SRV_TraspasoAfore_doc_dt_contextoTransaccional dt_contextoTransaccional = 7;
}
message AF_SRV_TraspasoAfore_doc_dt_contextoTransaccional {
optional  string txId = 1;
optional  string txStartDate = 2;
optional  string stepId = 3;
optional  string processDefinitionName = 4;
optional  string processInstanceId = 5;
optional  string customProcessInstanceId = 6;
optional  string taskId = 7;
optional  string customTaskId = 8;
optional  string stepName = 9;
optional  string applicationUserId = 10;
optional  string executorUserId = 11;
optional  string stopInstance = 12;
optional  string completeTask = 13;
}
message AF_SRV_TraspasoAfore_doc_dt_comparador_output {
optional  string resultado = 8;
}
message pub_publish_envelope {
optional  string activation = 1;
optional  int32 appLastSeqn = 2;
optional  string appPassword = 3;
optional  int32 appSeqn = 4;
optional  string appUserName = 5;
optional  int32 priority = 6;
optional  string businessContext = 7;
repeated  int32 controlLabel = 8;
optional  string errorsTo = 9;
optional  string errorRequestsTo = 10;
optional  string locale = 11;
optional  int32 maxResults = 12;
optional  string replyTo = 13;
optional  int32 runLevel = 14;
optional  bytes signature = 15;
optional  string signatureType = 16;
optional  int32 startResult = 17;
optional  int32 tag = 18;
optional  string trackId = 19;
optional  string transactionId = 20;
optional  string transformState = 21;
optional  int32 age = 22;
optional  string connectionIntegrity = 23;
optional  string destId = 24;
optional  int64 enqueueTime = 25;
optional  string logBroker = 26;
optional  string logHost = 27;
optional  string pubDistinguishedName = 28;
optional  string pubId = 29;
optional  bytes pubNetAddr = 30;
optional  int64 pubSeqn = 31;
repeated  int32 pubLabel = 32;
optional  int64 recvTime = 33;
repeated  pub_publish_envelope_route route = 34;
optional  string uuid = 35;
optional  string status = 36;
}
message pub_publish_envelope_route {
optional  string broker = 1;
optional  int64 recvTime = 2;
optional  int64 enqueueTime = 3;
}
