<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">publish</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGEgaW5wdXQgPSBJRGF0YVV0aWwuZ2V0SURhdGEocGlwZWxpbmUuZ2V0Q3Vyc29yKCksICJP
bmJvYXJkaW5nQ2xpZW50Iik7DQpTdHJpbmcgZG9jVHlwZSA9ICJwcm9jZXNzZXMuUFAwMTpPbmJv
YXJkaW5nQ2xpZW50IjsNCg0KSURhdGEgZG9jdW1lbnQgPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7
DQpJRGF0YVV0aWwucHV0KGRvY3VtZW50LmdldEN1cnNvcigpLCAiZG9jdW1lbnRUeXBlTmFtZSIs
IGRvY1R5cGUpOw0KSURhdGFVdGlsLnB1dChkb2N1bWVudC5nZXRDdXJzb3IoKSwgImRvY3VtZW50
IiwgaW5wdXQpOw0KDQp0cnkgew0KICAgIFNlcnZpY2VUaHJlYWQgb3V0ID0gU2VydmljZS5kb1Ro
cmVhZEludm9rZSgicHViLnB1Ymxpc2giLCAicHVibGlzaCIsIGRvY3VtZW50LCAobG9uZykgMTAw
MCk7DQogICAgDQogICAgSURhdGFVdGlsLnB1dChwaXBlbGluZS5nZXRDdXJzb3IoKSwgInJlc3Vs
dCIsIG91dC5nZXRJRGF0YSgpKTsNCn0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7DQogICAgLy8gVE9E
TyBBdXRvLWdlbmVyYXRlZCBjYXRjaCBibG9jaw0KICAgIGUucHJpbnRTdGFja1RyYWNlKCk7DQog
ICAgSURhdGFVdGlsLnB1dChwaXBlbGluZS5nZXRDdXJzb3IoKSwgImVycm9yIiwgZS5nZXRNZXNz
YWdlKCkgKyBlLmdldENhdXNlKCkgKyBlLmdldENhdXNlKCkpOw0KfQ==</value>
</Values>
