#wmtaskclient
#Wed Aug 12 20:07:12 UTC 2026
taskclienturl=http\://10.209.23.56\:8585
taskserver=REMOTE_MWS
taskclienttimeout=60000
taskclientusejms=false
taskclientuser=Administrator
taskclientretrydelay=1000
taskclientimpersonateacl=
taskclientretries=0
