<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">cleanupSession</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZU1hcCA9IG5ldyBJRGF0YU1hcChwaXBlbGluZSk7CmJvb2xlYW4gZGVidWcg
PSBnZXREZWJ1ZyggcGlwZU1hcCApOwkJClN0cmluZyBzZXNzaW9uSWQgPSBnZXRTZXNzaW9uSWQo
IHBpcGVNYXAgKTsKCmJvb2xlYW4gcmVwb3J0ZXJSZW1vdmVkID0gSlNQTWFuYWdlci5nZXRJbnN0
YW5jZSgpLnJlbW92ZVJlcG9ydGVyKCBzZXNzaW9uSWQgKTsKYm9vbGVhbiB0b2tlbnNSZW1vdmVk
ID0gSlNQTWFuYWdlci5nZXRJbnN0YW5jZSgpLnJlbW92ZVRlbXBsYXRlVG9rZW5zKCBzZXNzaW9u
SWQgKTsKaWYgKCBkZWJ1ZykgewoJU3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoIlxu
WyVzXTolcyIsICJjbGVhbnVwU2Vzc2lvbiIsIG5ldyBqYXZhLnV0aWwuRGF0ZSgpKSk7CQkJCglT
eXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiU2Vzc2lvbklkOiAlcywgUmVwb3J0ZXIg
cmVtb3ZlZD8gJXMsIFRlbXBsYXRlIFRva2VuIHJlbW92ZWQ/ICVzIiwgCgkJCXNlc3Npb25JZCwg
cmVwb3J0ZXJSZW1vdmVkLCB0b2tlbnNSZW1vdmVkKSk7CQkJCn0KdHJ5IHsKCWlmICggZGVidWcp
IHsKCQlTeXN0ZW0uZXJyLnByaW50bG4oIkNhbGxpbmcgd20uc2VydmVyOmxvZ291dCBmb3IgQXBw
IFBsYXRmb3JtIGpzcDpjbGVhbnVwU2Vzc2lvbiBzZXJ2aWNlIik7CgkJU3lzdGVtLmVyci5wcmlu
dGxuKCJ3YXR0LnNlY3VyaXR5LnNlc3Npb24uZm9yY2VSZWF1dGhPbkV4cGlyYXRpb24gPSAiICsK
CQkJCUNvbmZpZy5nZXRQcm9wZXJ0eSggIndhdHQuc2VjdXJpdHkuc2Vzc2lvbi5mb3JjZVJlYXV0
aE9uRXhwaXJhdGlvbiIpKTsKCX0KCVNlcnZpY2UuZG9JbnZva2UoIndtLnNlcnZlciIsICJsb2dv
dXQiLCBuZXcgSURhdGFNYXAoKS5nZXRJRGF0YSgpKTsKCWlmICggZGVidWcpIHsKCQlTeXN0ZW0u
ZXJyLnByaW50bG4oIlNlc3Npb24gZGVzdHJveWVkLiIpOwoJfQp9IGNhdGNoIChFeGNlcHRpb24g
ZSkgewoJaWYgKCBkZWJ1ZykgewoJCVN5c3RlbS5lcnIucHJpbnRsbigiRXhjZXB0aW9uIGNhbGxp
bmcgd20uc2VydmVyOmxvZ291dCBJUyBzZXJ2aWNlIGZvciBBcHAgUGxhdGZvcm0gc2Vzc2lvbiIp
OwoJCWUucHJpbnRTdGFja1RyYWNlKCk7Cgl9Cn0KCg==</value>
</Values>
